version: '2'

services:

  consul:
    image: consul
    container_name: consul
    mem_limit: 512M
    ports:
     - "8500:8500"
     - "8300:8300"

  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    container_name: customers-service
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512M
    depends_on:
      - consul
      - tracing-server
    entrypoint: ["./dockerize","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]

  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    container_name: visits-service
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512M
    depends_on:
      - consul
      - tracing-server
    entrypoint: ["./dockerize","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]

  vets-service:
    image: springcommunity/spring-petclinic-vets-service
    container_name: vets-service
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512M
    depends_on:
      - consul
      - tracing-server
    entrypoint: ["./dockerize","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]

  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    container_name: api-gateway
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512M
    depends_on:
      - consul
      - tracing-server
    entrypoint: ["./dockerize","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - "8080:8080"

  admin-server:
    image: springcommunity/spring-petclinic-admin-server
    container_name: admin-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512M
    depends_on:
      - consul
    entrypoint: ["./dockerize","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - "9090:9090"

  ## Grafana / Prometheus / Zipkin

  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    mem_limit: 256M
    ports:
     - "3000:3000"

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    mem_limit: 256M
    ports:
     - "9091:9090"

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    environment:
     - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
     - "9411:9411"
